// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrate/CLI tooling should hit the direct (non-pooled) connection when one
    // is configured (e.g. Neon in production); falls back to DATABASE_URL locally.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
